version: '3'

services:
  jira_container:
    container_name: jira_container
    restart: always
    image: atlassian/jira-software
    ports:
      - 8080:8080
    volumes:
      - ./jira/jira_data:/var/atlassian/application-data/jira
    environment:
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: "${DBUSER}"
      ATL_JDBC_PASSWORD: "${DBPASSWORD}"
      ATL_DB_TYPE: postgres72
      ATL_JDBC_URL: jdbc:postgresql://postgres_db_jira:5432/test_post_jira
    networks:
      atlassian_network:
        ipv4_address: 172.28.1.1

  confluence_container:
    restart: always
    container_name: confluence_container
    image: atlassian/confluence-server
    ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - ./confluence/confluence_data:/var/atlassian/application-data/confluence
    environment:
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: "${DBUSER}"
      ATL_JDBC_PASSWORD: "${DBPASSWORD}"
      ATL_DB_TYPE: postgresql
      ATL_JDBC_URL: jdbc:postgresql://postgres_db_jira:5432/test_post_confluence
    networks:
      atlassian_network:
        ipv4_address: 172.28.1.2

  postgres_db_jira:
    container_name: postgres_db
    image: postgres:9.6-alpine
    ports:
      - 40699:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_dbs_script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_MULTIPLE_DATABASES: test_post_jira,test_post_confluence
      #Unused credential to create 1 db
      #POSTGRES_DB:
    networks:
      atlassian_network:
        ipv4_address: 172.28.1.3

volumes:
  postgres_data:

networks:
  atlassian_network:
    ipam:
      driver: default
      config:
       - subnet: 172.28.0.0/16
